-- liquibase formatted sql

CREATE TABLE date_periodicity (
    id UUID NOT NULL,
    date VARCHAR(255),
    CONSTRAINT pk_date_periodicity PRIMARY KEY (id)
);

CREATE TABLE participants (
    id UUID NOT NULL,
    chat_id VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    patronymic VARCHAR(255),
    date_periodicity_id UUID,
    CONSTRAINT pk_participants PRIMARY KEY (id)
);

CREATE TABLE periodicity (
    id UUID NOT NULL,
    title VARCHAR(255),
    chat_id VARCHAR(255),
    description VARCHAR(1220),
    date_periodicity_id UUID,
    CONSTRAINT pk_periodicity PRIMARY KEY (id));

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id));

ALTER TABLE participants
    ADD CONSTRAINT fk_participants_date_periodicity
    FOREIGN KEY (date_periodicity_id)
    REFERENCES date_periodicity (id)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;

ALTER TABLE periodicity
    ADD CONSTRAINT fk_periodicity_date_periodicity
    FOREIGN KEY (date_periodicity_id)
    REFERENCES date_periodicity (id)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;

